### ISSUE TITLE
Control Remapping Issues

### ISSUE THREAD

**Issue by vinceeleazar** [FlashyReese/ping-fabric#3]
Good day, 
So I tested this mod and found out a "bug" of some sorts I guess. Basically when you remap the default control "v" to another key the hud does not stay still on your screen and it flickers. 

Maybe this video will help describe the scenario I am referring to. 
https://gfycat.com/deliciouswavybullfrog

Here's the [log](https://paste.ee/p/Dpolb) if ever needed as well.
I know the mod is still in the early stages, but I'm reporting since this is probably not an intended behavior. Anyways, thanks for creating this mod!

**Comment by FlashyReese** [comment]
Thank you for the issue report, I have pushed a fix for it. I will release an update to address it tomorrow :D

**Comment by vinceeleazar** [comment]
Ohhh that was fast. Thanks for the very quick response
