### ISSUE TITLE
Crash with REI 5.8.2

### ISSUE THREAD

**Issue by shouxd** [FlashyReese/ping-fabric#7]
Crash log:
https://pastebin.com/FWXLh9V1

Latest.log:
https://pastebin.com/Skdiyd2k

Reported to REI and dev said: "Ping mod hardcoded requirements for Cloth Config versioning."

**Comment by FlashyReese** [comment]
I have fixed this in f9c4118, I will release an update as soon as possible you can use the build from GitHub Actions https://github.com/FlashyReese/ping-fabric/actions/runs/356514779
