### ISSUE TITLE
Glowing effect

### ISSUE THREAD

**Issue by shouxd** [FlashyReese/ping-fabric#8]
Hi again! When using build in Github Actions, Ping mod prevents the white outline of the "glowing" effect from appearing, showing yellow spiral particle effects instead.

**Comment by FlashyReese** [comment]
I assume you mean glowing effect from spectral arrows, unless it's something else can you provide some screenshots.

**Comment by shouxd** [comment]
Yes, glowing outline (i.e from spectral arrows) is just missing:

![image](https://user-images.githubusercontent.com/59116327/99116487-1c15b580-25c2-11eb-8e61-356bfd50da68.png)
