### ISSUE TITLE
Incompatable with REI

### ISSUE THREAD

**Issue by Fusion-Flux** [FlashyReese/ping-fabric#9]
When used with REI it causes a crash here are the logs
https://pastebin.com/S1dQSWNW

**Comment by FlashyReese** [comment]
What version is this? I have already fixed this in Ping 1.2.1

**Comment by Fusion-Flux** [comment]
oh modrinth has janky positioning for mod updates sorry about that

**Comment by Fusion-Flux** [comment]
i was using 1.2.0

**Comment by FlashyReese** [comment]
No problem ^^
